language: php
sudo: false

services:
  - postgresql

matrix:
  fast_finish: true
  include:
    - php: "7.3"
    - php: "nightly"
    - php: "master"
  allow_failures:
    - php: "nightly"
    - php: "master"

before_install:
  - chmod +x tests/travis-install.sh

install:
  - composer update
  - tests/travis-install.sh

script:
  - vendor/bin/phpunit
